export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  INVENTORY: "/inventory",
  NEW_ITEM: "/inventory/new",
  SETTINGS_CATEGORIES: "/settings/categories",
  SETTINGS_SUBCATEGORIES: "/settings/subcategories",
  SETTINGS_UNITS: "/settings/units",
  SETTINGS_SUPPLIERS: "/settings/suppliers",
  login: "/login",
  dashboard: "/dashboard",
  inventory: "/inventory",
  inventoryNew: "/inventory/new",
  inventoryEdit: (id: number | string) => `/inventory/${id}/edit`,
  settingsCategories: "/settings/categories",
  settingsSubcategories: "/settings/subcategories",
  settingsUnits: "/settings/units",
  settingsSuppliers: "/settings/suppliers",
} as const;
